# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68855b5e979840f3ea0795934a3bbef324dd6e11b5a067a55ab0231d28bc1cad943cec27113da10ee0b932e8caf6559a9bd4ca5ab46a77dc6fc10c94c8b936a5

test:
  secret_key_base: 7a2fbc108fd73e7b5f3513a4c7e0c8f41938355b32313efa98515dcf9d4dd650ad602b5c8bb009747e7c4e9a53b18b36657e3f177d9de31a6c69cb31e74519bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
